name: Continuous Fuzzing

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    name: Fuzz
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          go get github.com/dvyukov/go-fuzz/go-fuzz-build

      - name: Build
        run: |
          go-fuzz-build -func FuzzRuleParser -o sigma-go-rule-fuzz.zip
          go-fuzz-build -func FuzzConfigParser -o sigma-go-config-fuzz.zip
          go-fuzz-build -func FuzzConditionParser -o sigma-go-condition-fuzz.zip

      - name: Upload
        run: |
          wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/latest/download/fuzzit_Linux_x86_64
          chmod a+x fuzzit
          ./fuzzit create target --skip-if-exists sigma-go
          ./fuzzit create job --engine go-fuzz --type fuzzing sigma-go/rule ./sigma-go-rule-fuzz.zip
          ./fuzzit create job --engine go-fuzz --type fuzzing sigma-go/config ./sigma-go-config-fuzz.zip
          ./fuzzit create job --engine go-fuzz --type fuzzing sigma-go/condition ./sigma-go-condition-fuzz.zip
        env:
          FUZZIT_API_KEY: ${{ secrets.FUZZIT_API_KEY }}
